# Generated by Django 6.0.8 on 2026-08-06 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attractions', '0001_initial'),
        ('tickets', '0003_alter_ticket_valid_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('attraction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions.attraction')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
    ]
