# Generated by Django 6.0.8 on 2026-08-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnstile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanlog',
            old_name='attraction_id',
            new_name='attraction',
        ),
        migrations.RenameField(
            model_name='scanlog',
            old_name='ticket_id',
            new_name='ticket',
        ),
    ]
