# Generated by Django 6.0.8 on 2026-08-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_discountcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCategory',
        ),
    ]
