# Generated by Django 6.0.8 on 2026-08-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('operation_status', models.CharField(choices=[('running', 'Running'), ('down_weather', 'Down Weather'), ('down_mechanical', 'Down Mechanical'), ('closed', 'Closed')], max_length=20)),
            ],
        ),
    ]
