# Generated by Django 6.0.8 on 2026-08-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='min_height_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
