# Generated by Django 6.0.8 on 2026-08-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_valid_from_ticket_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
