# Generated by Django 6.0.8 on 2026-08-06 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
        ('tickets', '0003_alter_ticket_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='guest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guests.guest'),
            preserve_default=False,
        ),
    ]
