# Generated by Django 6.0.8 on 2026-08-06 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
        ('tickets', '0004_ticket_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=59.99, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='guests.guest'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='valid_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
