# Generated by Django 6.0.8 on 2026-08-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_price_alter_ticket_guest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('discount_percent', models.PositiveIntegerField()),
            ],
        ),
    ]
