# Generated by Django 6.0.8 on 2026-08-07 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_discountcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCategory',
        ),
    ]
